FROM node:16-bullseye

# Install app dependencies
# A wildcard is used to ensure both package.json AND package-lock.json are copied
# where available (npm@5+)
WORKDIR /src/Gateways/Gateway.NodeDemo
# COPY  ./Node.Demo/sample-upc-nodejs ./
COPY ["./Node.Demo", "./"]

RUN npm install
# If you are building your code for production
# RUN npm ci --only=production

EXPOSE 8000

# Bundle app source
CMD [ "npm", "run", "start" ]